"""email field and soft delete in user

Revision ID: 2b82378bd149
Revises: e583583df5db
Create Date: 2026-05-26 17:12:33.076608

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b82378bd149'
down_revision: Union[str, Sequence[str], None] = 'e583583df5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_owner_id_fkey'), 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'library_user', ['owner_id'], ['id'])
    op.add_column('library_user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('library_user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_library_user_email'), 'library_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_user_email'), table_name='library_user')
    op.drop_column('library_user', 'is_active')
    op.drop_column('library_user', 'email')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key(op.f('book_owner_id_fkey'), 'book', 'library_user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
