"""Added return states and ledger due date

Revision ID: 2e0671484b2f
Revises: 2b82378bd149
Create Date: 2026-05-26 20:08:18.489297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0671484b2f'
down_revision: Union[str, Sequence[str], None] = '2b82378bd149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_ledger', sa.Column('due_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_ledger', 'due_date')
    # ### end Alembic commands ###
