"""database anomalies fixes

Revision ID: 8e130120da20
Revises: f29232ac2b05
Create Date: 2026-05-24 19:37:23.214607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e130120da20'
down_revision: Union[str, Sequence[str], None] = 'f29232ac2b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow_ledger', 'book_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('borrow_ledger_book_id_fkey'), 'borrow_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'borrow_ledger', 'book', ['book_id'], ['id'], ondelete='SET NULL')
    op.add_column('library_user', sa.Column('version_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_user', 'version_id')
    op.drop_constraint(None, 'borrow_ledger', type_='foreignkey')
    op.create_foreign_key(op.f('borrow_ledger_book_id_fkey'), 'borrow_ledger', 'book', ['book_id'], ['id'])
    op.alter_column('borrow_ledger', 'book_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
