"""soft delets and temporal integrity

Revision ID: e583583df5db
Revises: 8e130120da20
Create Date: 2026-05-24 19:57:03.342675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e583583df5db'
down_revision: Union[str, Sequence[str], None] = '8e130120da20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('is_deleted', sa.Boolean(), nullable=False,server_default=sa.text("false")))
    op.create_index(op.f('ix_book_is_deleted'), 'book', ['is_deleted'], unique=False)
    op.alter_column('borrow_ledger', 'book_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('borrow_ledger_book_id_fkey'), 'borrow_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'borrow_ledger', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrow_ledger', type_='foreignkey')
    op.create_foreign_key(op.f('borrow_ledger_book_id_fkey'), 'borrow_ledger', 'book', ['book_id'], ['id'], ondelete='SET NULL')
    op.alter_column('borrow_ledger', 'book_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_book_is_deleted'), table_name='book')
    op.drop_column('book', 'is_deleted')
    # ### end Alembic commands ###
