"""added book_request queue

Revision ID: f29232ac2b05
Revises: 5d2a56d5a3e2
Create Date: 2026-05-24 15:57:19.905459

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29232ac2b05'
down_revision: Union[str, Sequence[str], None] = '5d2a56d5a3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELED', name='requeststatus'), nullable=False),
    sa.Column('owner_notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['library_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiver_id', 'book_id', 'status', name='uq_active_user_book_request')
    )
    op.create_index(op.f('ix_book_request_book_id'), 'book_request', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_request_receiver_id'), 'book_request', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_book_request_status'), 'book_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_request_status'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_receiver_id'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_book_id'), table_name='book_request')
    op.drop_table('book_request')
    # ### end Alembic commands ###
